/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables.records;


import com.example.onboardingservice.jooq.tables.OnboardingHrs;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OnboardingHrsRecord extends UpdatableRecordImpl<OnboardingHrsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.onboarding_hrs.chat_id</code>.
     */
    public void setChatId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.onboarding_hrs.chat_id</code>.
     */
    public Long getChatId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.onboarding_hrs.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.onboarding_hrs.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.onboarding_hrs.first_name</code>.
     */
    public void setFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.onboarding_hrs.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.onboarding_hrs.last_name</code>.
     */
    public void setLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.onboarding_hrs.last_name</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OnboardingHrsRecord
     */
    public OnboardingHrsRecord() {
        super(OnboardingHrs.ONBOARDING_HRS);
    }

    /**
     * Create a detached, initialised OnboardingHrsRecord
     */
    public OnboardingHrsRecord(Long chatId, String username, String firstName, String lastName) {
        super(OnboardingHrs.ONBOARDING_HRS);

        setChatId(chatId);
        setUsername(username);
        setFirstName(firstName);
        setLastName(lastName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OnboardingHrsRecord
     */
    public OnboardingHrsRecord(com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs value) {
        super(OnboardingHrs.ONBOARDING_HRS);

        if (value != null) {
            setChatId(value.getChatId());
            setUsername(value.getUsername());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            resetChangedOnNotNull();
        }
    }
}
