/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables.records;


import com.example.onboardingservice.jooq.tables.OnboardingProperties;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OnboardingPropertiesRecord extends UpdatableRecordImpl<OnboardingPropertiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.onboarding_properties.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.onboarding_properties.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.onboarding_properties.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.onboarding_properties.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.onboarding_properties.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.onboarding_properties.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OnboardingPropertiesRecord
     */
    public OnboardingPropertiesRecord() {
        super(OnboardingProperties.ONBOARDING_PROPERTIES);
    }

    /**
     * Create a detached, initialised OnboardingPropertiesRecord
     */
    public OnboardingPropertiesRecord(String name, String description, String value) {
        super(OnboardingProperties.ONBOARDING_PROPERTIES);

        setName(name);
        setDescription(description);
        setValue(value);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OnboardingPropertiesRecord
     */
    public OnboardingPropertiesRecord(com.example.onboardingservice.jooq.tables.pojos.OnboardingProperties value) {
        super(OnboardingProperties.ONBOARDING_PROPERTIES);

        if (value != null) {
            setName(value.getName());
            setDescription(value.getDescription());
            setValue(value.getValue());
            resetChangedOnNotNull();
        }
    }
}
