/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables.records;


import com.example.onboardingservice.jooq.tables.OnboardingHrs;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OnboardingHrsRecord extends UpdatableRecordImpl<OnboardingHrsRecord> implements Record4<Long, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.onboarding_hrs.chat_id</code>.
     */
    public void setChatId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.onboarding_hrs.chat_id</code>.
     */
    public Long getChatId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.onboarding_hrs.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.onboarding_hrs.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.onboarding_hrs.first_name</code>.
     */
    public void setFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.onboarding_hrs.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.onboarding_hrs.last_name</code>.
     */
    public void setLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.onboarding_hrs.last_name</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OnboardingHrs.ONBOARDING_HRS.CHAT_ID;
    }

    @Override
    public Field<String> field2() {
        return OnboardingHrs.ONBOARDING_HRS.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return OnboardingHrs.ONBOARDING_HRS.FIRST_NAME;
    }

    @Override
    public Field<String> field4() {
        return OnboardingHrs.ONBOARDING_HRS.LAST_NAME;
    }

    @Override
    public Long component1() {
        return getChatId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getFirstName();
    }

    @Override
    public String component4() {
        return getLastName();
    }

    @Override
    public Long value1() {
        return getChatId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getFirstName();
    }

    @Override
    public String value4() {
        return getLastName();
    }

    @Override
    public OnboardingHrsRecord value1(Long value) {
        setChatId(value);
        return this;
    }

    @Override
    public OnboardingHrsRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public OnboardingHrsRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public OnboardingHrsRecord value4(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public OnboardingHrsRecord values(Long value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OnboardingHrsRecord
     */
    public OnboardingHrsRecord() {
        super(OnboardingHrs.ONBOARDING_HRS);
    }

    /**
     * Create a detached, initialised OnboardingHrsRecord
     */
    public OnboardingHrsRecord(Long chatId, String username, String firstName, String lastName) {
        super(OnboardingHrs.ONBOARDING_HRS);

        setChatId(chatId);
        setUsername(username);
        setFirstName(firstName);
        setLastName(lastName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OnboardingHrsRecord
     */
    public OnboardingHrsRecord(com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs value) {
        super(OnboardingHrs.ONBOARDING_HRS);

        if (value != null) {
            setChatId(value.getChatId());
            setUsername(value.getUsername());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            resetChangedOnNotNull();
        }
    }
}
