/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables.records;


import com.example.onboardingservice.jooq.tables.ScenarioRouteDefinition;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScenarioRouteDefinitionRecord extends UpdatableRecordImpl<ScenarioRouteDefinitionRecord> implements Record3<String, JSONB, JSONB> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.scenario_route_definition.scenario_name</code>.
     */
    public void setScenarioName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.scenario_route_definition.scenario_name</code>.
     */
    public String getScenarioName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.scenario_route_definition.route_source</code>.
     */
    public void setRouteSource(JSONB value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.scenario_route_definition.route_source</code>.
     */
    public JSONB getRouteSource() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>public.scenario_route_definition.matcher</code>.
     */
    public void setMatcher(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.scenario_route_definition.matcher</code>.
     */
    public JSONB getMatcher() {
        return (JSONB) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, JSONB, JSONB> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, JSONB, JSONB> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION.SCENARIO_NAME;
    }

    @Override
    public Field<JSONB> field2() {
        return ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION.ROUTE_SOURCE;
    }

    @Override
    public Field<JSONB> field3() {
        return ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION.MATCHER;
    }

    @Override
    public String component1() {
        return getScenarioName();
    }

    @Override
    public JSONB component2() {
        return getRouteSource();
    }

    @Override
    public JSONB component3() {
        return getMatcher();
    }

    @Override
    public String value1() {
        return getScenarioName();
    }

    @Override
    public JSONB value2() {
        return getRouteSource();
    }

    @Override
    public JSONB value3() {
        return getMatcher();
    }

    @Override
    public ScenarioRouteDefinitionRecord value1(String value) {
        setScenarioName(value);
        return this;
    }

    @Override
    public ScenarioRouteDefinitionRecord value2(JSONB value) {
        setRouteSource(value);
        return this;
    }

    @Override
    public ScenarioRouteDefinitionRecord value3(JSONB value) {
        setMatcher(value);
        return this;
    }

    @Override
    public ScenarioRouteDefinitionRecord values(String value1, JSONB value2, JSONB value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScenarioRouteDefinitionRecord
     */
    public ScenarioRouteDefinitionRecord() {
        super(ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION);
    }

    /**
     * Create a detached, initialised ScenarioRouteDefinitionRecord
     */
    public ScenarioRouteDefinitionRecord(String scenarioName, JSONB routeSource, JSONB matcher) {
        super(ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION);

        setScenarioName(scenarioName);
        setRouteSource(routeSource);
        setMatcher(matcher);
        resetChangedOnNotNull();
    }
}
