/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables.records;


import com.example.onboardingservice.jooq.tables.Scenario;
import org.jooq.*;
import org.jooq.impl.UpdatableRecordImpl;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScenarioRecord extends UpdatableRecordImpl<ScenarioRecord> implements Record7<UUID, String, Long, UUID, Boolean, UUID, JSONB> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.scenario.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.scenario.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.scenario.scenario_name</code>.
     */
    public void setScenarioName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.scenario.scenario_name</code>.
     */
    public String getScenarioName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.scenario.chat_id</code>.
     */
    public void setChatId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.scenario.chat_id</code>.
     */
    public Long getChatId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.scenario.current_action_id</code>.
     */
    public void setCurrentActionId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.scenario.current_action_id</code>.
     */
    public UUID getCurrentActionId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.scenario.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.scenario.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.scenario.first_action_id</code>.
     */
    public void setFirstActionId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.scenario.first_action_id</code>.
     */
    public UUID getFirstActionId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.scenario.context</code>.
     */
    public void setContext(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.scenario.context</code>.
     */
    public JSONB getContext() {
        return (JSONB) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, String, Long, UUID, Boolean, UUID, JSONB> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, String, Long, UUID, Boolean, UUID, JSONB> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Scenario.SCENARIO.ID;
    }

    @Override
    public Field<String> field2() {
        return Scenario.SCENARIO.SCENARIO_NAME;
    }

    @Override
    public Field<Long> field3() {
        return Scenario.SCENARIO.CHAT_ID;
    }

    @Override
    public Field<UUID> field4() {
        return Scenario.SCENARIO.CURRENT_ACTION_ID;
    }

    @Override
    public Field<Boolean> field5() {
        return Scenario.SCENARIO.IS_ACTIVE;
    }

    @Override
    public Field<UUID> field6() {
        return Scenario.SCENARIO.FIRST_ACTION_ID;
    }

    @Override
    public Field<JSONB> field7() {
        return Scenario.SCENARIO.CONTEXT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getScenarioName();
    }

    @Override
    public Long component3() {
        return getChatId();
    }

    @Override
    public UUID component4() {
        return getCurrentActionId();
    }

    @Override
    public Boolean component5() {
        return getIsActive();
    }

    @Override
    public UUID component6() {
        return getFirstActionId();
    }

    @Override
    public JSONB component7() {
        return getContext();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getScenarioName();
    }

    @Override
    public Long value3() {
        return getChatId();
    }

    @Override
    public UUID value4() {
        return getCurrentActionId();
    }

    @Override
    public Boolean value5() {
        return getIsActive();
    }

    @Override
    public UUID value6() {
        return getFirstActionId();
    }

    @Override
    public JSONB value7() {
        return getContext();
    }

    @Override
    public ScenarioRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ScenarioRecord value2(String value) {
        setScenarioName(value);
        return this;
    }

    @Override
    public ScenarioRecord value3(Long value) {
        setChatId(value);
        return this;
    }

    @Override
    public ScenarioRecord value4(UUID value) {
        setCurrentActionId(value);
        return this;
    }

    @Override
    public ScenarioRecord value5(Boolean value) {
        setIsActive(value);
        return this;
    }

    @Override
    public ScenarioRecord value6(UUID value) {
        setFirstActionId(value);
        return this;
    }

    @Override
    public ScenarioRecord value7(JSONB value) {
        setContext(value);
        return this;
    }

    @Override
    public ScenarioRecord values(UUID value1, String value2, Long value3, UUID value4, Boolean value5, UUID value6, JSONB value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScenarioRecord
     */
    public ScenarioRecord() {
        super(Scenario.SCENARIO);
    }

    /**
     * Create a detached, initialised ScenarioRecord
     */
    public ScenarioRecord(UUID id, String scenarioName, Long chatId, UUID currentActionId, Boolean isActive, UUID firstActionId, JSONB context) {
        super(Scenario.SCENARIO);

        setId(id);
        setScenarioName(scenarioName);
        setChatId(chatId);
        setCurrentActionId(currentActionId);
        setIsActive(isActive);
        setFirstActionId(firstActionId);
        setContext(context);
        resetChangedOnNotNull();
    }
}
