/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables.records;


import com.example.onboardingservice.jooq.tables.ScenarioRouteDefinition;
import org.jooq.*;
import org.jooq.impl.UpdatableRecordImpl;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScenarioRouteDefinitionRecord extends UpdatableRecordImpl<ScenarioRouteDefinitionRecord> implements Record6<String, UUID, JSONB, JSONB, UUID, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.scenario_route_definition.scenario_name</code>.
     */
    public void setScenarioName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.scenario_route_definition.scenario_name</code>.
     */
    public String getScenarioName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.scenario_route_definition.first_action_id</code>.
     */
    public void setFirstActionId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.scenario_route_definition.first_action_id</code>.
     */
    public UUID getFirstActionId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.scenario_route_definition.route_source</code>.
     */
    public void setRouteSource(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.scenario_route_definition.route_source</code>.
     */
    public JSONB getRouteSource() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.scenario_route_definition.matcher</code>.
     */
    public void setMatcher(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.scenario_route_definition.matcher</code>.
     */
    public JSONB getMatcher() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.scenario_route_definition.id</code>.
     */
    public void setId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.scenario_route_definition.id</code>.
     */
    public UUID getId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.scenario_route_definition.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.scenario_route_definition.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, UUID, JSONB, JSONB, UUID, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, UUID, JSONB, JSONB, UUID, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION.SCENARIO_NAME;
    }

    @Override
    public Field<UUID> field2() {
        return ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION.FIRST_ACTION_ID;
    }

    @Override
    public Field<JSONB> field3() {
        return ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION.ROUTE_SOURCE;
    }

    @Override
    public Field<JSONB> field4() {
        return ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION.MATCHER;
    }

    @Override
    public Field<UUID> field5() {
        return ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION.ID;
    }

    @Override
    public Field<String> field6() {
        return ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION.STATUS;
    }

    @Override
    public String component1() {
        return getScenarioName();
    }

    @Override
    public UUID component2() {
        return getFirstActionId();
    }

    @Override
    public JSONB component3() {
        return getRouteSource();
    }

    @Override
    public JSONB component4() {
        return getMatcher();
    }

    @Override
    public UUID component5() {
        return getId();
    }

    @Override
    public String component6() {
        return getStatus();
    }

    @Override
    public String value1() {
        return getScenarioName();
    }

    @Override
    public UUID value2() {
        return getFirstActionId();
    }

    @Override
    public JSONB value3() {
        return getRouteSource();
    }

    @Override
    public JSONB value4() {
        return getMatcher();
    }

    @Override
    public UUID value5() {
        return getId();
    }

    @Override
    public String value6() {
        return getStatus();
    }

    @Override
    public ScenarioRouteDefinitionRecord value1(String value) {
        setScenarioName(value);
        return this;
    }

    @Override
    public ScenarioRouteDefinitionRecord value2(UUID value) {
        setFirstActionId(value);
        return this;
    }

    @Override
    public ScenarioRouteDefinitionRecord value3(JSONB value) {
        setRouteSource(value);
        return this;
    }

    @Override
    public ScenarioRouteDefinitionRecord value4(JSONB value) {
        setMatcher(value);
        return this;
    }

    @Override
    public ScenarioRouteDefinitionRecord value5(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ScenarioRouteDefinitionRecord value6(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ScenarioRouteDefinitionRecord values(String value1, UUID value2, JSONB value3, JSONB value4, UUID value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScenarioRouteDefinitionRecord
     */
    public ScenarioRouteDefinitionRecord() {
        super(ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION);
    }

    /**
     * Create a detached, initialised ScenarioRouteDefinitionRecord
     */
    public ScenarioRouteDefinitionRecord(String scenarioName, UUID firstActionId, JSONB routeSource, JSONB matcher, UUID id, String status) {
        super(ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION);

        setScenarioName(scenarioName);
        setFirstActionId(firstActionId);
        setRouteSource(routeSource);
        setMatcher(matcher);
        setId(id);
        setStatus(status);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ScenarioRouteDefinitionRecord
     */
    public ScenarioRouteDefinitionRecord(com.example.onboardingservice.jooq.tables.pojos.ScenarioRouteDefinition value) {
        super(ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION);

        if (value != null) {
            setScenarioName(value.getScenarioName());
            setFirstActionId(value.getFirstActionId());
            setRouteSource(value.getRouteSource());
            setMatcher(value.getMatcher());
            setId(value.getId());
            setStatus(value.getStatus());
            resetChangedOnNotNull();
        }
    }
}
