/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables.records;


import com.example.onboardingservice.jooq.tables.Scenario;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScenarioRecord extends UpdatableRecordImpl<ScenarioRecord> implements Record5<UUID, String, Long, UUID, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.scenario.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.scenario.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.scenario.scenario_name</code>.
     */
    public void setScenarioName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.scenario.scenario_name</code>.
     */
    public String getScenarioName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.scenario.chat_id</code>.
     */
    public void setChatId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.scenario.chat_id</code>.
     */
    public Long getChatId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.scenario.current_action_id</code>.
     */
    public void setCurrentActionId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.scenario.current_action_id</code>.
     */
    public UUID getCurrentActionId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.scenario.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.scenario.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, String, Long, UUID, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, String, Long, UUID, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Scenario.SCENARIO.ID;
    }

    @Override
    public Field<String> field2() {
        return Scenario.SCENARIO.SCENARIO_NAME;
    }

    @Override
    public Field<Long> field3() {
        return Scenario.SCENARIO.CHAT_ID;
    }

    @Override
    public Field<UUID> field4() {
        return Scenario.SCENARIO.CURRENT_ACTION_ID;
    }

    @Override
    public Field<Boolean> field5() {
        return Scenario.SCENARIO.IS_ACTIVE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getScenarioName();
    }

    @Override
    public Long component3() {
        return getChatId();
    }

    @Override
    public UUID component4() {
        return getCurrentActionId();
    }

    @Override
    public Boolean component5() {
        return getIsActive();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getScenarioName();
    }

    @Override
    public Long value3() {
        return getChatId();
    }

    @Override
    public UUID value4() {
        return getCurrentActionId();
    }

    @Override
    public Boolean value5() {
        return getIsActive();
    }

    @Override
    public ScenarioRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ScenarioRecord value2(String value) {
        setScenarioName(value);
        return this;
    }

    @Override
    public ScenarioRecord value3(Long value) {
        setChatId(value);
        return this;
    }

    @Override
    public ScenarioRecord value4(UUID value) {
        setCurrentActionId(value);
        return this;
    }

    @Override
    public ScenarioRecord value5(Boolean value) {
        setIsActive(value);
        return this;
    }

    @Override
    public ScenarioRecord values(UUID value1, String value2, Long value3, UUID value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScenarioRecord
     */
    public ScenarioRecord() {
        super(Scenario.SCENARIO);
    }

    /**
     * Create a detached, initialised ScenarioRecord
     */
    public ScenarioRecord(UUID id, String scenarioName, Long chatId, UUID currentActionId, Boolean isActive) {
        super(Scenario.SCENARIO);

        setId(id);
        setScenarioName(scenarioName);
        setChatId(chatId);
        setCurrentActionId(currentActionId);
        setIsActive(isActive);
        resetChangedOnNotNull();
    }
}
