version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: onboarding
      POSTGRES_USER: onboarding
      POSTGRES_PASSWORD: onboarding
    volumes:
      - ./data/postgre:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_AOF_ENABLED=no
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 500mb
    ports:
      - "6379:6379"
  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "8443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  onboarding: