telegram:
  bot-name: ${TELEGRAM_BOT_NAME:}
  bot-token: ${TELEGRAM_BOT_TOKEN:}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
  liquibase:
    database-change-log-table: _databasechangelog
    database-change-log-lock-table: _databasechangeloglock
    change-log: classpath:/db/changelog/master.xml
