/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq;


import com.example.onboardingservice.jooq.tables.Scenario;
import com.example.onboardingservice.jooq.tables.ScenarioRouteDefinition;
import com.example.onboardingservice.jooq.tables._Databasechangelog;
import com.example.onboardingservice.jooq.tables._Databasechangeloglock;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public._databasechangelog</code>.
     */
    public final _Databasechangelog _DATABASECHANGELOG = _Databasechangelog._DATABASECHANGELOG;

    /**
     * The table <code>public._databasechangeloglock</code>.
     */
    public final _Databasechangeloglock _DATABASECHANGELOGLOCK = _Databasechangeloglock._DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.scenario</code>.
     */
    public final Scenario SCENARIO = Scenario.SCENARIO;

    /**
     * The table <code>public.scenario_route_definition</code>.
     */
    public final ScenarioRouteDefinition SCENARIO_ROUTE_DEFINITION = ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            _Databasechangelog._DATABASECHANGELOG,
            _Databasechangeloglock._DATABASECHANGELOGLOCK,
            Scenario.SCENARIO,
            ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION
        );
    }
}
