/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq;


import com.example.onboardingservice.jooq.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.onboarding_documents</code>.
     */
    public final OnboardingDocuments ONBOARDING_DOCUMENTS = OnboardingDocuments.ONBOARDING_DOCUMENTS;

    /**
     * The table <code>public.onboarding_hrs</code>.
     */
    public final OnboardingHrs ONBOARDING_HRS = OnboardingHrs.ONBOARDING_HRS;

    /**
     * The table <code>public.onboarding_properties</code>.
     */
    public final OnboardingProperties ONBOARDING_PROPERTIES = OnboardingProperties.ONBOARDING_PROPERTIES;

    /**
     * The table <code>public.scenario</code>.
     */
    public final Scenario SCENARIO = Scenario.SCENARIO;

    /**
     * The table <code>public.scenario_notification</code>.
     */
    public final ScenarioNotification SCENARIO_NOTIFICATION = ScenarioNotification.SCENARIO_NOTIFICATION;

    /**
     * The table <code>public.scenario_route_definition</code>.
     */
    public final ScenarioRouteDefinition SCENARIO_ROUTE_DEFINITION = ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            OnboardingDocuments.ONBOARDING_DOCUMENTS,
            OnboardingHrs.ONBOARDING_HRS,
            OnboardingProperties.ONBOARDING_PROPERTIES,
            Scenario.SCENARIO,
            ScenarioNotification.SCENARIO_NOTIFICATION,
            ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION
        );
    }
}
