/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq;


import com.example.onboardingservice.jooq.tables.Scenario;
import com.example.onboardingservice.jooq.tables.ScenarioRouteDefinition;
import com.example.onboardingservice.jooq.tables._Databasechangelog;
import com.example.onboardingservice.jooq.tables._Databasechangeloglock;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public._databasechangelog</code>.
     */
    public static final _Databasechangelog _DATABASECHANGELOG = _Databasechangelog._DATABASECHANGELOG;

    /**
     * The table <code>public._databasechangeloglock</code>.
     */
    public static final _Databasechangeloglock _DATABASECHANGELOGLOCK = _Databasechangeloglock._DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.scenario</code>.
     */
    public static final Scenario SCENARIO = Scenario.SCENARIO;

    /**
     * The table <code>public.scenario_route_definition</code>.
     */
    public static final ScenarioRouteDefinition SCENARIO_ROUTE_DEFINITION = ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION;
}
