/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq;


import com.example.onboardingservice.jooq.tables.*;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.onboarding_documents</code>.
     */
    public static final OnboardingDocuments ONBOARDING_DOCUMENTS = OnboardingDocuments.ONBOARDING_DOCUMENTS;

    /**
     * The table <code>public.onboarding_hrs</code>.
     */
    public static final OnboardingHrs ONBOARDING_HRS = OnboardingHrs.ONBOARDING_HRS;

    /**
     * The table <code>public.onboarding_properties</code>.
     */
    public static final OnboardingProperties ONBOARDING_PROPERTIES = OnboardingProperties.ONBOARDING_PROPERTIES;

    /**
     * The table <code>public.scenario</code>.
     */
    public static final Scenario SCENARIO = Scenario.SCENARIO;

    /**
     * The table <code>public.scenario_notification</code>.
     */
    public static final ScenarioNotification SCENARIO_NOTIFICATION = ScenarioNotification.SCENARIO_NOTIFICATION;

    /**
     * The table <code>public.scenario_route_definition</code>.
     */
    public static final ScenarioRouteDefinition SCENARIO_ROUTE_DEFINITION = ScenarioRouteDefinition.SCENARIO_ROUTE_DEFINITION;
}
