/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OnboardingProperties implements Serializable {

    private static final long serialVersionUID = 1L;

    private String name;
    private String description;
    private String value;

    public OnboardingProperties() {}

    public OnboardingProperties(OnboardingProperties value) {
        this.name = value.name;
        this.description = value.description;
        this.value = value.value;
    }

    public OnboardingProperties(
        String name,
        String description,
        String value
    ) {
        this.name = name;
        this.description = description;
        this.value = value;
    }

    /**
     * Getter for <code>public.onboarding_properties.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.onboarding_properties.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.onboarding_properties.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.onboarding_properties.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.onboarding_properties.value</code>.
     */
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>public.onboarding_properties.value</code>.
     */
    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OnboardingProperties other = (OnboardingProperties) obj;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OnboardingProperties (");

        sb.append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
