/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OnboardingDocuments implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID key;
    private String filename;

    public OnboardingDocuments() {}

    public OnboardingDocuments(OnboardingDocuments value) {
        this.key = value.key;
        this.filename = value.filename;
    }

    public OnboardingDocuments(
        UUID key,
        String filename
    ) {
        this.key = key;
        this.filename = filename;
    }

    /**
     * Getter for <code>public.onboarding_documents.key</code>.
     */
    public UUID getKey() {
        return this.key;
    }

    /**
     * Setter for <code>public.onboarding_documents.key</code>.
     */
    public void setKey(UUID key) {
        this.key = key;
    }

    /**
     * Getter for <code>public.onboarding_documents.filename</code>.
     */
    public String getFilename() {
        return this.filename;
    }

    /**
     * Setter for <code>public.onboarding_documents.filename</code>.
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OnboardingDocuments other = (OnboardingDocuments) obj;
        if (this.key == null) {
            if (other.key != null)
                return false;
        }
        else if (!this.key.equals(other.key))
            return false;
        if (this.filename == null) {
            if (other.filename != null)
                return false;
        }
        else if (!this.filename.equals(other.filename))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.key == null) ? 0 : this.key.hashCode());
        result = prime * result + ((this.filename == null) ? 0 : this.filename.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OnboardingDocuments (");

        sb.append(key);
        sb.append(", ").append(filename);

        sb.append(")");
        return sb.toString();
    }
}
