/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables.pojos;


import org.jooq.JSONB;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Scenario implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String scenarioName;
    private Long chatId;
    private UUID currentActionId;
    private Boolean isActive;
    private UUID firstActionId;
    private JSONB context;

    public Scenario() {}

    public Scenario(Scenario value) {
        this.id = value.id;
        this.scenarioName = value.scenarioName;
        this.chatId = value.chatId;
        this.currentActionId = value.currentActionId;
        this.isActive = value.isActive;
        this.firstActionId = value.firstActionId;
        this.context = value.context;
    }

    public Scenario(
        UUID id,
        String scenarioName,
        Long chatId,
        UUID currentActionId,
        Boolean isActive,
        UUID firstActionId,
        JSONB context
    ) {
        this.id = id;
        this.scenarioName = scenarioName;
        this.chatId = chatId;
        this.currentActionId = currentActionId;
        this.isActive = isActive;
        this.firstActionId = firstActionId;
        this.context = context;
    }

    /**
     * Getter for <code>public.scenario.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.scenario.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.scenario.scenario_name</code>.
     */
    public String getScenarioName() {
        return this.scenarioName;
    }

    /**
     * Setter for <code>public.scenario.scenario_name</code>.
     */
    public void setScenarioName(String scenarioName) {
        this.scenarioName = scenarioName;
    }

    /**
     * Getter for <code>public.scenario.chat_id</code>.
     */
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>public.scenario.chat_id</code>.
     */
    public void setChatId(Long chatId) {
        this.chatId = chatId;
    }

    /**
     * Getter for <code>public.scenario.current_action_id</code>.
     */
    public UUID getCurrentActionId() {
        return this.currentActionId;
    }

    /**
     * Setter for <code>public.scenario.current_action_id</code>.
     */
    public void setCurrentActionId(UUID currentActionId) {
        this.currentActionId = currentActionId;
    }

    /**
     * Getter for <code>public.scenario.is_active</code>.
     */
    public Boolean getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for <code>public.scenario.is_active</code>.
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * Getter for <code>public.scenario.first_action_id</code>.
     */
    public UUID getFirstActionId() {
        return this.firstActionId;
    }

    /**
     * Setter for <code>public.scenario.first_action_id</code>.
     */
    public void setFirstActionId(UUID firstActionId) {
        this.firstActionId = firstActionId;
    }

    /**
     * Getter for <code>public.scenario.context</code>.
     */
    public JSONB getContext() {
        return this.context;
    }

    /**
     * Setter for <code>public.scenario.context</code>.
     */
    public void setContext(JSONB context) {
        this.context = context;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Scenario other = (Scenario) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.scenarioName == null) {
            if (other.scenarioName != null)
                return false;
        }
        else if (!this.scenarioName.equals(other.scenarioName))
            return false;
        if (this.chatId == null) {
            if (other.chatId != null)
                return false;
        }
        else if (!this.chatId.equals(other.chatId))
            return false;
        if (this.currentActionId == null) {
            if (other.currentActionId != null)
                return false;
        }
        else if (!this.currentActionId.equals(other.currentActionId))
            return false;
        if (this.isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!this.isActive.equals(other.isActive))
            return false;
        if (this.firstActionId == null) {
            if (other.firstActionId != null)
                return false;
        }
        else if (!this.firstActionId.equals(other.firstActionId))
            return false;
        if (this.context == null) {
            if (other.context != null)
                return false;
        }
        else if (!this.context.equals(other.context))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.scenarioName == null) ? 0 : this.scenarioName.hashCode());
        result = prime * result + ((this.chatId == null) ? 0 : this.chatId.hashCode());
        result = prime * result + ((this.currentActionId == null) ? 0 : this.currentActionId.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        result = prime * result + ((this.firstActionId == null) ? 0 : this.firstActionId.hashCode());
        result = prime * result + ((this.context == null) ? 0 : this.context.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Scenario (");

        sb.append(id);
        sb.append(", ").append(scenarioName);
        sb.append(", ").append(chatId);
        sb.append(", ").append(currentActionId);
        sb.append(", ").append(isActive);
        sb.append(", ").append(firstActionId);
        sb.append(", ").append(context);

        sb.append(")");
        return sb.toString();
    }
}
