/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables.pojos;


import org.jooq.JSONB;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScenarioRouteDefinition implements Serializable {

    private static final long serialVersionUID = 1L;

    private String scenarioName;
    private UUID firstActionId;
    private JSONB routeSource;
    private JSONB matcher;
    private UUID id;
    private String status;

    public ScenarioRouteDefinition() {}

    public ScenarioRouteDefinition(ScenarioRouteDefinition value) {
        this.scenarioName = value.scenarioName;
        this.firstActionId = value.firstActionId;
        this.routeSource = value.routeSource;
        this.matcher = value.matcher;
        this.id = value.id;
        this.status = value.status;
    }

    public ScenarioRouteDefinition(
        String scenarioName,
        UUID firstActionId,
        JSONB routeSource,
        JSONB matcher,
        UUID id,
        String status
    ) {
        this.scenarioName = scenarioName;
        this.firstActionId = firstActionId;
        this.routeSource = routeSource;
        this.matcher = matcher;
        this.id = id;
        this.status = status;
    }

    /**
     * Getter for <code>public.scenario_route_definition.scenario_name</code>.
     */
    public String getScenarioName() {
        return this.scenarioName;
    }

    /**
     * Setter for <code>public.scenario_route_definition.scenario_name</code>.
     */
    public void setScenarioName(String scenarioName) {
        this.scenarioName = scenarioName;
    }

    /**
     * Getter for <code>public.scenario_route_definition.first_action_id</code>.
     */
    public UUID getFirstActionId() {
        return this.firstActionId;
    }

    /**
     * Setter for <code>public.scenario_route_definition.first_action_id</code>.
     */
    public void setFirstActionId(UUID firstActionId) {
        this.firstActionId = firstActionId;
    }

    /**
     * Getter for <code>public.scenario_route_definition.route_source</code>.
     */
    public JSONB getRouteSource() {
        return this.routeSource;
    }

    /**
     * Setter for <code>public.scenario_route_definition.route_source</code>.
     */
    public void setRouteSource(JSONB routeSource) {
        this.routeSource = routeSource;
    }

    /**
     * Getter for <code>public.scenario_route_definition.matcher</code>.
     */
    public JSONB getMatcher() {
        return this.matcher;
    }

    /**
     * Setter for <code>public.scenario_route_definition.matcher</code>.
     */
    public void setMatcher(JSONB matcher) {
        this.matcher = matcher;
    }

    /**
     * Getter for <code>public.scenario_route_definition.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.scenario_route_definition.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.scenario_route_definition.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.scenario_route_definition.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ScenarioRouteDefinition other = (ScenarioRouteDefinition) obj;
        if (this.scenarioName == null) {
            if (other.scenarioName != null)
                return false;
        }
        else if (!this.scenarioName.equals(other.scenarioName))
            return false;
        if (this.firstActionId == null) {
            if (other.firstActionId != null)
                return false;
        }
        else if (!this.firstActionId.equals(other.firstActionId))
            return false;
        if (this.routeSource == null) {
            if (other.routeSource != null)
                return false;
        }
        else if (!this.routeSource.equals(other.routeSource))
            return false;
        if (this.matcher == null) {
            if (other.matcher != null)
                return false;
        }
        else if (!this.matcher.equals(other.matcher))
            return false;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.scenarioName == null) ? 0 : this.scenarioName.hashCode());
        result = prime * result + ((this.firstActionId == null) ? 0 : this.firstActionId.hashCode());
        result = prime * result + ((this.routeSource == null) ? 0 : this.routeSource.hashCode());
        result = prime * result + ((this.matcher == null) ? 0 : this.matcher.hashCode());
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ScenarioRouteDefinition (");

        sb.append(scenarioName);
        sb.append(", ").append(firstActionId);
        sb.append(", ").append(routeSource);
        sb.append(", ").append(matcher);
        sb.append(", ").append(id);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
