/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables;


import com.example.onboardingservice.jooq.Keys;
import com.example.onboardingservice.jooq.Public;
import com.example.onboardingservice.jooq.tables.records.OnboardingDocumentsRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.UUID;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OnboardingDocuments extends TableImpl<OnboardingDocumentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.onboarding_documents</code>
     */
    public static final OnboardingDocuments ONBOARDING_DOCUMENTS = new OnboardingDocuments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OnboardingDocumentsRecord> getRecordType() {
        return OnboardingDocumentsRecord.class;
    }

    /**
     * The column <code>public.onboarding_documents.key</code>.
     */
    public final TableField<OnboardingDocumentsRecord, UUID> KEY = createField(DSL.name("key"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.onboarding_documents.filename</code>.
     */
    public final TableField<OnboardingDocumentsRecord, String> FILENAME = createField(DSL.name("filename"), SQLDataType.VARCHAR(512).nullable(false), this, "");

    private OnboardingDocuments(Name alias, Table<OnboardingDocumentsRecord> aliased) {
        this(alias, aliased, null);
    }

    private OnboardingDocuments(Name alias, Table<OnboardingDocumentsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.onboarding_documents</code> table
     * reference
     */
    public OnboardingDocuments(String alias) {
        this(DSL.name(alias), ONBOARDING_DOCUMENTS);
    }

    /**
     * Create an aliased <code>public.onboarding_documents</code> table
     * reference
     */
    public OnboardingDocuments(Name alias) {
        this(alias, ONBOARDING_DOCUMENTS);
    }

    /**
     * Create a <code>public.onboarding_documents</code> table reference
     */
    public OnboardingDocuments() {
        this(DSL.name("onboarding_documents"), null);
    }

    public <O extends Record> OnboardingDocuments(Table<O> child, ForeignKey<O, OnboardingDocumentsRecord> key) {
        super(child, key, ONBOARDING_DOCUMENTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OnboardingDocumentsRecord> getPrimaryKey() {
        return Keys.ONBOARDING_DOCUMENTS_PKEY;
    }

    @Override
    public OnboardingDocuments as(String alias) {
        return new OnboardingDocuments(DSL.name(alias), this);
    }

    @Override
    public OnboardingDocuments as(Name alias) {
        return new OnboardingDocuments(alias, this);
    }

    @Override
    public OnboardingDocuments as(Table<?> alias) {
        return new OnboardingDocuments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OnboardingDocuments rename(String name) {
        return new OnboardingDocuments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OnboardingDocuments rename(Name name) {
        return new OnboardingDocuments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OnboardingDocuments rename(Table<?> name) {
        return new OnboardingDocuments(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super UUID, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super UUID, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
