/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables;


import com.example.onboardingservice.jooq.Keys;
import com.example.onboardingservice.jooq.Public;
import com.example.onboardingservice.jooq.tables.records.OnboardingHrsRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OnboardingHrs extends TableImpl<OnboardingHrsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.onboarding_hrs</code>
     */
    public static final OnboardingHrs ONBOARDING_HRS = new OnboardingHrs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OnboardingHrsRecord> getRecordType() {
        return OnboardingHrsRecord.class;
    }

    /**
     * The column <code>public.onboarding_hrs.chat_id</code>.
     */
    public final TableField<OnboardingHrsRecord, Long> CHAT_ID = createField(DSL.name("chat_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.onboarding_hrs.username</code>.
     */
    public final TableField<OnboardingHrsRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.onboarding_hrs.first_name</code>.
     */
    public final TableField<OnboardingHrsRecord, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.onboarding_hrs.last_name</code>.
     */
    public final TableField<OnboardingHrsRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(255), this, "");

    private OnboardingHrs(Name alias, Table<OnboardingHrsRecord> aliased) {
        this(alias, aliased, null);
    }

    private OnboardingHrs(Name alias, Table<OnboardingHrsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.onboarding_hrs</code> table reference
     */
    public OnboardingHrs(String alias) {
        this(DSL.name(alias), ONBOARDING_HRS);
    }

    /**
     * Create an aliased <code>public.onboarding_hrs</code> table reference
     */
    public OnboardingHrs(Name alias) {
        this(alias, ONBOARDING_HRS);
    }

    /**
     * Create a <code>public.onboarding_hrs</code> table reference
     */
    public OnboardingHrs() {
        this(DSL.name("onboarding_hrs"), null);
    }

    public <O extends Record> OnboardingHrs(Table<O> child, ForeignKey<O, OnboardingHrsRecord> key) {
        super(child, key, ONBOARDING_HRS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OnboardingHrsRecord> getPrimaryKey() {
        return Keys.ONBOARDING_HRS_PKEY;
    }

    @Override
    public OnboardingHrs as(String alias) {
        return new OnboardingHrs(DSL.name(alias), this);
    }

    @Override
    public OnboardingHrs as(Name alias) {
        return new OnboardingHrs(alias, this);
    }

    @Override
    public OnboardingHrs as(Table<?> alias) {
        return new OnboardingHrs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OnboardingHrs rename(String name) {
        return new OnboardingHrs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OnboardingHrs rename(Name name) {
        return new OnboardingHrs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OnboardingHrs rename(Table<?> name) {
        return new OnboardingHrs(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
