/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables;


import com.example.onboardingservice.jooq.Keys;
import com.example.onboardingservice.jooq.Public;
import com.example.onboardingservice.jooq.tables.records.ScenarioNotificationRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.UUID;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScenarioNotification extends TableImpl<ScenarioNotificationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.scenario_notification</code>
     */
    public static final ScenarioNotification SCENARIO_NOTIFICATION = new ScenarioNotification();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScenarioNotificationRecord> getRecordType() {
        return ScenarioNotificationRecord.class;
    }

    /**
     * The column <code>public.scenario_notification.id</code>.
     */
    public final TableField<ScenarioNotificationRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.scenario_notification.chat_id</code>.
     */
    public final TableField<ScenarioNotificationRecord, Long> CHAT_ID = createField(DSL.name("chat_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.scenario_notification.message</code>.
     */
    public final TableField<ScenarioNotificationRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.scenario_notification.repeat</code>.
     */
    public final TableField<ScenarioNotificationRecord, Boolean> REPEAT = createField(DSL.name("repeat"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.scenario_notification.delay</code>.
     */
    public final TableField<ScenarioNotificationRecord, String> DELAY = createField(DSL.name("delay"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.scenario_notification.status</code>.
     */
    public final TableField<ScenarioNotificationRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.scenario_notification.next_execution</code>.
     */
    public final TableField<ScenarioNotificationRecord, OffsetDateTime> NEXT_EXECUTION = createField(DSL.name("next_execution"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private ScenarioNotification(Name alias, Table<ScenarioNotificationRecord> aliased) {
        this(alias, aliased, null);
    }

    private ScenarioNotification(Name alias, Table<ScenarioNotificationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.scenario_notification</code> table
     * reference
     */
    public ScenarioNotification(String alias) {
        this(DSL.name(alias), SCENARIO_NOTIFICATION);
    }

    /**
     * Create an aliased <code>public.scenario_notification</code> table
     * reference
     */
    public ScenarioNotification(Name alias) {
        this(alias, SCENARIO_NOTIFICATION);
    }

    /**
     * Create a <code>public.scenario_notification</code> table reference
     */
    public ScenarioNotification() {
        this(DSL.name("scenario_notification"), null);
    }

    public <O extends Record> ScenarioNotification(Table<O> child, ForeignKey<O, ScenarioNotificationRecord> key) {
        super(child, key, SCENARIO_NOTIFICATION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ScenarioNotificationRecord> getPrimaryKey() {
        return Keys.SCENARIO_NOTIFICATION_PKEY;
    }

    @Override
    public ScenarioNotification as(String alias) {
        return new ScenarioNotification(DSL.name(alias), this);
    }

    @Override
    public ScenarioNotification as(Name alias) {
        return new ScenarioNotification(alias, this);
    }

    @Override
    public ScenarioNotification as(Table<?> alias) {
        return new ScenarioNotification(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScenarioNotification rename(String name) {
        return new ScenarioNotification(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScenarioNotification rename(Name name) {
        return new ScenarioNotification(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScenarioNotification rename(Table<?> name) {
        return new ScenarioNotification(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, Long, String, Boolean, String, String, OffsetDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super UUID, ? super Long, ? super String, ? super Boolean, ? super String, ? super String, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super UUID, ? super Long, ? super String, ? super Boolean, ? super String, ? super String, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
