/*
 * This file is generated by jOOQ.
 */
package com.example.onboardingservice.jooq.tables.daos;


import com.example.onboardingservice.jooq.AbstractSpringDAOImpl;
import com.example.onboardingservice.jooq.tables.OnboardingHrs;
import com.example.onboardingservice.jooq.tables.records.OnboardingHrsRecord;
import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class OnboardingHrsDao extends AbstractSpringDAOImpl<OnboardingHrsRecord, com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs, Long> {

    /**
     * Create a new OnboardingHrsDao without any configuration
     */
    public OnboardingHrsDao() {
        super(OnboardingHrs.ONBOARDING_HRS, com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs.class);
    }

    /**
     * Create a new OnboardingHrsDao with an attached configuration
     */
    @Autowired
    public OnboardingHrsDao(Configuration configuration) {
        super(OnboardingHrs.ONBOARDING_HRS, com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs.class, configuration);
    }

    @Override
    public Long getId(com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs object) {
        return object.getChatId();
    }

    /**
     * Fetch records that have <code>chat_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs> fetchRangeOfChatId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(OnboardingHrs.ONBOARDING_HRS.CHAT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>chat_id IN (values)</code>
     */
    public List<com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs> fetchByChatId(Long... values) {
        return fetch(OnboardingHrs.ONBOARDING_HRS.CHAT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>chat_id = value</code>
     */
    public com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs fetchOneByChatId(Long value) {
        return fetchOne(OnboardingHrs.ONBOARDING_HRS.CHAT_ID, value);
    }

    /**
     * Fetch a unique record that has <code>chat_id = value</code>
     */
    public Optional<com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs> fetchOptionalByChatId(Long value) {
        return fetchOptional(OnboardingHrs.ONBOARDING_HRS.CHAT_ID, value);
    }

    /**
     * Fetch records that have <code>username BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs> fetchRangeOfUsername(String lowerInclusive, String upperInclusive) {
        return fetchRange(OnboardingHrs.ONBOARDING_HRS.USERNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs> fetchByUsername(String... values) {
        return fetch(OnboardingHrs.ONBOARDING_HRS.USERNAME, values);
    }

    /**
     * Fetch records that have <code>first_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs> fetchRangeOfFirstName(String lowerInclusive, String upperInclusive) {
        return fetchRange(OnboardingHrs.ONBOARDING_HRS.FIRST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs> fetchByFirstName(String... values) {
        return fetch(OnboardingHrs.ONBOARDING_HRS.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs> fetchRangeOfLastName(String lowerInclusive, String upperInclusive) {
        return fetchRange(OnboardingHrs.ONBOARDING_HRS.LAST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<com.example.onboardingservice.jooq.tables.pojos.OnboardingHrs> fetchByLastName(String... values) {
        return fetch(OnboardingHrs.ONBOARDING_HRS.LAST_NAME, values);
    }
}
